import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Introduction } from "@/components/Introduction";
import { ListWork } from "@/components/ListWork";
import { Skills } from "@/components/Skills";
import { motion, useScroll } from "framer-motion";
import { usePortfolioContext } from "@/context/PortfolioContext";
import { About } from "@/components/About";

export default function Home() {
  const { job, name, github, picture, abouts } = usePortfolioContext();
  const { scrollYProgress } = useScroll();
  const title = `${job} - ${name}`;
  const schema = {
    "@context": "http://schema.org",
    "@type": "Person",
    name: name,
    sameAs: github,
    jobTitle: job,
    description: abouts[0],
    image: picture,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Paris",
      addressCountry: "France",
    },
  };
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="application/ld+json"></script>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />
      </Head>
      <main>
        <motion.div
          style={{ scaleX: scrollYProgress }}
          className={styles.progressBar}
        />
        <article>
          <Introduction />
          <Skills />
          <ListWork />
          <About />
        </article>
      </main>
    </>
  );
}
